name: master-branch

on:
  push:
    branches:
      - 'master'

jobs:
  build-signed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build release
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ALIAS_PWD }} \

      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{ steps.sign_apk_release.outputs.signedReleaseFile }} artifacts/app-release.apk
          echo "::set-output name=path::artifacts/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ steps.artifacts_copy.outputs.path }}