name: master-branch

on:
  push:
    branches:
      [test]

env:
  KEYSTORE_PASSWORD: ${{ secrets.ALIAS_PWD }}
  KEYSTORE_ALIAS: ${{ secrets.ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

jobs:
  build-signed:
    name: Build Signed apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
#        name: set up JDK 11
        with:
          java-version: 11

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS }}
          path: app/keystore

      - name: Build release
        run: |
          ./gradlew assembleRelease

      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp app/build/outputs/apk/release/app-release.apk artifacts/app-release.apk
          echo "::set-output name=path::artifacts/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ steps.artifacts_copy.outputs.path }}